home:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: home.html.twig

what_is_backseat:
  path: /what
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: what_is_backseat.html.twig

i_did_not:
  path: /i-did-not
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: never_played.twig

but_the_caster_asked:
  path: /but-the-caster-asked
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: but_the_caster_asked.twig

