root:
  path: /
  controller: App\Controller\RootController:root

home:
  path: /{_locale}/
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: home.html.twig
  requirements:
    _locale: en|fr

what_is_backseat:
  path: /{_locale}/what-is-backseat
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: what_is_backseat.html.twig
  requirements:
    _locale: en|fr

never_played:
  path: /{_locale}/but-i-never-played-that-game
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: never_played.twig
  requirements:
    _locale: en|fr

but_the_caster_asked:
  path: /{_locale}/but-the-streamer-asked
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: but_the_caster_asked.twig
  requirements:
    _locale: en|fr

thank_you:
  path: /{_locale}/thank-you
  controller: App\Controller\IUnderstandController:index
  requirements:
    _locale: en|fr

twitch_redirect:
  path: /twitch_redirect

logout:
  path: /logout