name: PHP Composer

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      -   uses: actions/checkout@v2

      -   name: Validate composer.json and composer.lock
          run: composer validate --strict

      -   name: Cache Composer packages
          id: composer-cache
          uses: actions/cache@v2
          with:
            path: vendor
            key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
            restore-keys: |
              ${{ runner.os }}-php-
      -   name: Install dependencies
          run: composer install --prefer-dist --no-progress --no-suggest

      -   name: PHPStan code quality check
          run: vendor/bin/phpstan -n analyse src/

      -   name: php-cs-fixer code quality check
          run: vendor/bin/php-cs-fixer fix --config=./.php_cs.dist -v --dry-run --stop-on-violation --using-cache=no